export const sport_detalis = [
  {
    image: "/istockphoto-522201885-612x612.jpg",
    width: "500",
    height: "500",
    type: "normal",
    events: "48",
    sports: "Baseball",
    name: "Sacramento River Cats",
  },
  {
    image: "/istockphoto-522201885-612x612.jpg",
    width: "500",
    height: "500",
    type: "normal",
    events: "28",
    sports: "Baseball",
    name: "Las Vegas Aviators",
  },
  {
    image: "/istockphoto-522201885-612x612.jpg",
    width: "500",
    height: "500",
    type: "normal",
    events: "15",
    sports: "Ice Hockey",
    name: "New Jersey Devils",
  },
  {
    image: "/istockphoto-522201885-612x612.jpg",
    width: "500",
    height: "500",
    type: "normal",
    events: "28",
    sports: "Baseball",
    name: "Las Vegas Aviators",
  },
  {
    image: "/istockphoto-522201885-612x612.jpg",
    width: "500",
    height: "500",
    type: "ad",
    title: "Advertisement Title",
    about:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa enim, ab incidunt iusto temporibus, ad aperiam sint namy        suscipit quasi totam. Officiis iusto esse, error harum dolores suscipit",
  },
];

export const collection_detalis = [
  {
    image: "/istockphoto-522201885-612x612.jpg",
    text: "take flight collection",
    width: "500",
    height: "500",
    month: "OCT 15",
    day: "SUN",
    time: "4:30 PM",
    Address: "las vegas ballpark, las vegas, Nevada",
    name: "Las Vegas Aviators",
  },
  {
    image: "/istockphoto-522201885-612x612.jpg",
    text: "Orange Collection",
    width: "500",
    height: "500",
    month: "OCT 15",
    day: "SUN",
    time: "4:30 PM",
    Address: "Sutter health Park, sacramento, california",
    name: "Sacramento River Cats",
  },
  {
    image: "/istockphoto-522201885-612x612.jpg",
    text: "take flight collection",
    width: "500",
    height: "500",
    month: "OCT 15",
    day: "SUN",
    time: "4:30 PM",
    Address: "las vegas ballpark, las vegas, Nevada",
    name: "Las Vegas Aviators",
  },
  {
    image: "/istockphoto-522201885-612x612.jpg",
    text: "Orange Collection",
    width: "500",
    height: "500",
    month: "OCT 15",
    day: "SUN",
    time: "4:30 PM",
    Address: "Sutter health Park, sacramento, california",
    name: "Sacramento River Cats",
  },
];
